#! /bin/sh

#wal -i $HOME/.config/wallpapers/tokyonight.jpg &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config top_padding 20

bspc config window_gap 5

bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true
bspc config border_radius 8

bspc config split_ratio 0.50
bspc config gapless_monocle true

bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a code-oss desktop='^3' follow=on
bspc rule -a Steam desktop='^7' follow=off
bspc rule -a Zathura state=tiled

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true

~/.fehbg &
$HOME/.config/polybar/launch.sh 
dunst &
picom &
